const express = require("express")
const mongoose = require("mongoose")
const cors = require("cors")
const {router} = require("./routes/route")
require("dotenv").config()
const app = express()
app.use(express.json())
app.use(cors())
app.use("/uploads",express.static("uploads"))
app.use("/products",router)
mongoose.connect(process.env.CS).then(res=>{
    console.log("db connected")
})
app.listen(process.env.PORT,(res)=>{
    console.log(`Port is listening in ${process.env.PORT}`)
})