import type { User } from "../Types/auth";
import type { Department, ActivityLogEntry } from "../Types/core";
import type { Job, Candidate, Application } from "../Types/recruitment";
import type { Restaurant, Audit } from "../Types/audit";

export const seedDepartments: Department[] = [
  {
    id: "dep_hr",
    name: "Human Resources",
    description: "Recruitment, onboarding and people operations.",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "dep_ops",
    name: "Operations",
    description: "Restaurant network operations, audits and quality control.",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
];

export const seedUsers: User[] = [
  {
    id: "usr_admin",
    name: "Admin User",
    email: "admin@inop.com",
    password: "password123",
    role: "admin",
    departmentId: "dep_ops",
    position: "System Administrator",
    isActive: true,
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "usr_hr",
    name: "Aysel Huseynova",
    email: "hr@inop.com",
    password: "password123",
    role: "hr",
    departmentId: "dep_hr",
    position: "HR Manager",
    isActive: true,
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "usr_auditor",
    name: "Kamran Aliyev",
    email: "auditor@inop.com",
    password: "password123",
    role: "auditor",
    departmentId: "dep_ops",
    position: "Field Auditor",
    isActive: true,
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "usr_manager",
    name: "Nigar Mammadova",
    email: "manager@inop.com",
    password: "password123",
    role: "manager",
    departmentId: "dep_ops",
    position: "Operations Manager",
    isActive: true,
    createdAt: "2026-01-10T09:00:00.000Z",
  },
];

export const seedJobs: Job[] = [
  {
    id: "job_backend",
    position: "Backend Developer",
    description:
      "Build and maintain REST APIs for the internal operations platform.",
    requiredSkills: ["Node.js", "Express", "MongoDB"],
    preferredSkills: ["TypeScript", "Docker"],
    experience: 2,
    status: "open",
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "job_hr",
    position: "HR Specialist",
    description: "Support recruitment workflows and candidate screening.",
    requiredSkills: ["Recruitment", "Communication"],
    preferredSkills: ["HRIS"],
    experience: 1,
    status: "open",
    createdAt: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "job_auditor",
    position: "Restaurant Auditor",
    description: "Conduct on-site quality audits across the restaurant network.",
    requiredSkills: ["Attention to Detail", "Reporting"],
    preferredSkills: ["Food Safety Certification"],
    experience: 3,
    status: "closed",
    createdAt: "2026-06-15T10:00:00.000Z",
  },
];

export const seedCandidates: Candidate[] = [
  {
    id: "cand_1",
    name: "Elvin Guliyev",
    email: "elvin.guliyev@example.com",
    phone: "+994 50 123 45 67",
    education: "BSc Computer Science, ADA University",
    experience: 3,
    skills: ["Node.js", "Express", "MongoDB", "TypeScript"],
    languages: ["Azerbaijani", "English"],
    certificates: ["AWS Cloud Practitioner"],
    status: "shortlisted",
    cv: null,
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "cand_2",
    name: "Leyla Ismayilova",
    email: "leyla.ismayilova@example.com",
    phone: "+994 55 234 56 78",
    education: "BA Human Resources, Baku State University",
    experience: 1,
    skills: ["Recruitment", "Communication", "HRIS"],
    languages: ["Azerbaijani", "English", "Russian"],
    certificates: [],
    status: "screening",
    cv: null,
    createdAt: "2026-08-03T09:00:00.000Z",
  },
  {
    id: "cand_3",
    name: "Rashad Mammadli",
    email: "rashad.mammadli@example.com",
    phone: "+994 70 345 67 89",
    education: "BSc Software Engineering, UNEC",
    experience: 1,
    skills: ["Node.js", "MongoDB"],
    languages: ["Azerbaijani"],
    certificates: [],
    status: "new",
    cv: null,
    createdAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: "cand_4",
    name: "Sabina Rzayeva",
    email: "sabina.rzayeva@example.com",
    phone: "+994 51 456 78 90",
    education: "MSc Food Safety Management",
    experience: 4,
    skills: ["Attention to Detail", "Reporting", "Food Safety Certification"],
    languages: ["Azerbaijani", "English"],
    certificates: ["HACCP Certified"],
    status: "hired",
    cv: null,
    createdAt: "2026-06-20T09:00:00.000Z",
  },
  {
    id: "cand_5",
    name: "Tural Nagiyev",
    email: "tural.nagiyev@example.com",
    phone: "+994 77 567 89 01",
    education: "BSc Computer Engineering, Khazar University",
    experience: 0,
    skills: ["Node.js"],
    languages: ["Azerbaijani", "English"],
    certificates: [],
    status: "rejected",
    cv: null,
    createdAt: "2026-08-12T09:00:00.000Z",
  },
  {
    id: "cand_6",
    name: "Gunay Aslanova",
    email: "gunay.aslanova@example.com",
    phone: "+994 50 678 90 12",
    education: "BA Business Administration, ADA University",
    experience: 2,
    skills: ["Recruitment", "Communication"],
    languages: ["Azerbaijani", "English", "Turkish"],
    certificates: ["SHRM-CP"],
    status: "new",
    cv: null,
    createdAt: "2026-08-15T09:00:00.000Z",
  },
];

export const seedApplications: Application[] = [
  {
    id: "app_1",
    jobId: "job_backend",
    candidateId: "cand_1",
    status: "shortlisted",
    score: 0,
    appliedAt: "2026-08-02T09:00:00.000Z",
  },
  {
    id: "app_2",
    jobId: "job_backend",
    candidateId: "cand_3",
    status: "applied",
    score: 0,
    appliedAt: "2026-08-11T09:00:00.000Z",
  },
  {
    id: "app_3",
    jobId: "job_backend",
    candidateId: "cand_5",
    status: "rejected",
    score: 0,
    appliedAt: "2026-08-13T09:00:00.000Z",
  },
  {
    id: "app_4",
    jobId: "job_hr",
    candidateId: "cand_2",
    status: "screening",
    score: 0,
    appliedAt: "2026-08-04T09:00:00.000Z",
  },
  {
    id: "app_5",
    jobId: "job_hr",
    candidateId: "cand_6",
    status: "applied",
    score: 0,
    appliedAt: "2026-08-16T09:00:00.000Z",
  },
  {
    id: "app_6",
    jobId: "job_auditor",
    candidateId: "cand_4",
    status: "hired",
    score: 0,
    appliedAt: "2026-06-21T09:00:00.000Z",
  },
];

export const seedRestaurants: Restaurant[] = [
  {
    id: "rest_a",
    name: "Restaurant A - Nizami",
    location: "Baku, Nizami Street",
    status: "active",
    createdAt: "2026-01-15T09:00:00.000Z",
  },
  {
    id: "rest_b",
    name: "Restaurant B - Ganjlik",
    location: "Baku, Ganjlik Mall",
    status: "active",
    createdAt: "2026-01-15T09:00:00.000Z",
  },
  {
    id: "rest_c",
    name: "Restaurant C - Ganja",
    location: "Ganja, City Center",
    status: "active",
    createdAt: "2026-02-01T09:00:00.000Z",
  },
  {
    id: "rest_d",
    name: "Restaurant D - Sumgait",
    location: "Sumgait, 24th Microdistrict",
    status: "inactive",
    createdAt: "2026-02-10T09:00:00.000Z",
  },
];

export const seedAudits: Audit[] = [
  {
    id: "aud_1",
    restaurantId: "rest_a",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-06-08",
    scores: { cleanliness: 8, service: 8, food: 9, staff: 8 },
    comments: "Solid overall performance, minor delays during peak hours.",
    photos: [],
    attachments: [],
    createdAt: "2026-06-08T14:00:00.000Z",
  },
  {
    id: "aud_2",
    restaurantId: "rest_a",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-07-08",
    scores: { cleanliness: 7, service: 7, food: 8, staff: 8 },
    comments: "Service slowed down due to staff shortage.",
    photos: [],
    attachments: [],
    createdAt: "2026-07-08T14:00:00.000Z",
  },
  {
    id: "aud_3",
    restaurantId: "rest_a",
    auditorId: "usr_auditor",
    auditType: "Follow-up",
    date: "2026-08-08",
    scores: { cleanliness: 9, service: 9, food: 9, staff: 9 },
    comments: "Excellent improvement since last audit.",
    photos: [],
    attachments: [],
    createdAt: "2026-08-08T14:00:00.000Z",
  },
  {
    id: "aud_4",
    restaurantId: "rest_b",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-06-12",
    scores: { cleanliness: 8, service: 8, food: 9, staff: 7 },
    comments: "Kitchen hygiene above standard.",
    photos: [],
    attachments: [],
    createdAt: "2026-06-12T14:00:00.000Z",
  },
  {
    id: "aud_5",
    restaurantId: "rest_b",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-07-14",
    scores: { cleanliness: 8, service: 9, food: 8, staff: 8 },
    comments: "Consistent quality maintained.",
    photos: [],
    attachments: [],
    createdAt: "2026-07-14T14:00:00.000Z",
  },
  {
    id: "aud_6",
    restaurantId: "rest_b",
    auditorId: "usr_auditor",
    auditType: "Surprise",
    date: "2026-08-14",
    scores: { cleanliness: 9, service: 8, food: 9, staff: 9 },
    comments: "Great response under surprise visit conditions.",
    photos: [],
    attachments: [],
    createdAt: "2026-08-14T14:00:00.000Z",
  },
  {
    id: "aud_7",
    restaurantId: "rest_c",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-06-20",
    scores: { cleanliness: 6, service: 6, food: 7, staff: 6 },
    comments: "Below standard cleanliness in storage area.",
    photos: [],
    attachments: [],
    createdAt: "2026-06-20T14:00:00.000Z",
  },
  {
    id: "aud_8",
    restaurantId: "rest_c",
    auditorId: "usr_auditor",
    auditType: "Follow-up",
    date: "2026-07-20",
    scores: { cleanliness: 7, service: 7, food: 7, staff: 6 },
    comments: "Some improvement, storage area still needs attention.",
    photos: [],
    attachments: [],
    createdAt: "2026-07-20T14:00:00.000Z",
  },
  {
    id: "aud_9",
    restaurantId: "rest_c",
    auditorId: "usr_auditor",
    auditType: "Follow-up",
    date: "2026-08-20",
    scores: { cleanliness: 7, service: 7, food: 8, staff: 7 },
    comments: "Steady progress, re-check in a month.",
    photos: [],
    attachments: [],
    createdAt: "2026-08-20T14:00:00.000Z",
  },
  {
    id: "aud_10",
    restaurantId: "rest_d",
    auditorId: "usr_auditor",
    auditType: "Routine",
    date: "2026-07-02",
    scores: { cleanliness: 5, service: 6, food: 6, staff: 5 },
    comments: "Restaurant flagged for closure review.",
    photos: [],
    attachments: [],
    createdAt: "2026-07-02T14:00:00.000Z",
  },
];

export const seedActivityLogs: ActivityLogEntry[] = [
  {
    id: "log_1",
    userId: "usr_hr",
    userName: "Aysel Huseynova",
    action: "created",
    entityType: "Job",
    entityId: "job_backend",
    description: "Aysel Huseynova created Job \"Backend Developer\"",
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "log_2",
    userId: "usr_hr",
    userName: "Aysel Huseynova",
    action: "created",
    entityType: "Candidate",
    entityId: "cand_1",
    description: "Aysel Huseynova added Candidate \"Elvin Guliyev\"",
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "log_3",
    userId: "usr_auditor",
    userName: "Kamran Aliyev",
    action: "created",
    entityType: "Audit",
    entityId: "aud_3",
    description: "Kamran Aliyev submitted Audit #aud_3 for Restaurant A - Nizami",
    createdAt: "2026-08-08T14:00:00.000Z",
  },
];
